version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "auth-service"
        restart: unless-stopped
        ports:
            - "8082:3000"
